accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/advertisement_detail/<int:id>/', views.advertisement_detail, name='advertisement_detail'),
    path('profile/advertisement_detail/adv_edit/<int:id>', views.adv_edit, name='adv_edit'),

]

ad_page/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView

from ad_page import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="home"),
    path('admin/', admin.site.urls),
    path('ads/', include('ads.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

ads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'ads'

urlpatterns = [
                  path('', views.ads_list_view, name='list'),
                  path('add_advertisement/', views.add_advertisement, name='add_advertisement'),
                  path('<int:id>/', views.ads_detail_view, name='detail'),
                  path('transaction/<int:pk>/', views.create_transaction_view, name='create_transaction'),
                  path('reflink/<slug:slg>/', views.redirect_view, name='redirect'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, )
    balance = models.DecimalField(max_digits=10, decimal_places=4, default=0)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from ads.models import Advertisement


class AdvertisementEditForm(forms.ModelForm):
    action_value = forms.DecimalField(help_text="Please enter action value.", min_value=0)

    class Meta:
        model = Advertisement
        fields = ('title', 'action_value', 'page_url', 'img', 'status')

accounts/views.py
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.shortcuts import render, redirect


# Create your views here.
from accounts.forms import AdvertisementEditForm
from accounts.models import UserProfile
from ads.models import Advertisement, Transaction


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.save()
            user_profile = UserProfile.objects.create(user=new_user, balance=100)
            login(request, new_user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/accounts_signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('accounts:profile')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/accounts_login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


@login_required(login_url="/accounts/login/")
def profile_view(request):
    user = request.user.id
    ads = Advertisement.objects.all().filter(owner=user)
    user_profile = UserProfile.objects.get(user=user)
    transaction = Transaction.objects.filter(user_id=user)
    return render(request, 'accounts/profile.html', {'ads': ads, 'user_profile': user_profile,
                                                     'transaction': transaction})


@login_required(login_url="/accounts/login/")
def advertisement_detail(request, id):
    adv = Advertisement.objects.get(pk=id)
    return render(request, 'accounts/advertisement_detail.html', {'adv': adv})


@login_required(login_url="/accounts/login/")
def adv_edit(request, id):
    instance = Advertisement.objects.get(pk=id)
    if request.method == 'POST':
        edit_form = AdvertisementEditForm(instance=instance, data=request.POST, files=request.FILES)

        if edit_form.is_valid():
            edit_form.save()
            messages.success(request, 'Uaktualnienie reklamy ' \
                                      'zakończyło się sukcesem.')
        else:
            messages.error(request, 'Wystąpił błąd podczas uaktualniania reklamy.')
    else:
        edit_form = AdvertisementEditForm(instance=instance)

    return render(request, 'accounts/adv_edit.html', {'edit_form': edit_form})

accounts/templates/accounts/accounts_login.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block title %} Login {% endblock %}

{% block content %}
<div class="loginbox">
            <h1>Login Here</h1>
            <form action="{% url 'accounts:login' %}" method="POST">
              {% csrf_token %}
                <p>Username</p>
                <!--
                <input type="text" name="" placeholder="Enter Username">
                -->
                {{ form.username }}
                <p>Password</p>
                <!--
                <input type="password" name="" placeholder="Enter Password">
                -->
                {{ form.password }}
                {% if request.GET.next %}
                  <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <input type="submit" name="" value="Login">
                <a href="{% url 'accounts:signup' %}">Don't have an account?</a>

            </form>
        </div>
{% endblock %}

accounts/templates/accounts/accounts_signup.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block title %} Login {% endblock %}

{% block content %}
<div class="loginbox" style="height: 780px; width: 500px">
            <h1>Signup</h1>
    <form class="site-form" method="POST" action=".">
        {% csrf_token %}
                {{ form.as_p }}
                <br /><br />
                <input type="submit" value="Singup">

            </form>
    <a href="{% url 'accounts:login' %}">Already have an account? Sign in</a>
        </div>
{% endblock %}

accounts/templates/accounts/adv_edit.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block title %}Edycja reklamy{% endblock %}

{% block content %}
    <div class="loginbox" style="height: 780px; width: 500px">

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                        <a href="#" class="close">✖</a>
                    </li>
                {% endfor %}
            </ul>

        {% endif %}
        <h1>Edycja reklamy</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {{ edit_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Zapisz zmiany"></p>
        </form>
    </div>

{% endblock %}

accounts/templates/accounts/advertisement_detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block title %} Profil {% endblock %}

{% block content %}<br /><br /><br />
    <div class="container rounded" style="margin-top: 100px; background: #ffff; opacity: 0.95"><br />
      <div class="row">
        <div class="col-sm">
        <h1>Witaj : {{ user }}</h1>
        <h2 style="text-align: center">Informacje o reklamie: {{ adv.title }}</h2>

        <p>Status reklamy:{% if adv.status == 'active' %}
              <b><span class="badge badge-success">{{ adv.status }}</span></b> </br>{% else %}
              <b><span class="badge badge-secondary">{{ adv.status }}</span></b> </br>{% endif %}
        <p>Liczba użytkowników korzystających z reflinka: <b><span class="badge badge-light">{{ adv.adver.count }}</span></b></p>
        <p>Wartość akcji: <b>{{ adv.action_value }}</b></p>
        <p>Link do strony: <b>{{ adv.page_url }}</b></p>
        <button><a href="{% url 'accounts:adv_edit' id=adv.pk %}">Edytuj</a></button><br/><br/>
        </div>
        <div class="col-sm"><br/>
        <p><img src="{{ adv.img.url }}" class="img-thumbnail rounded float-right" width="230"></p>
        </div>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block title %} Profil {% endblock %}

{% block content %}
    <div class="container rounded" style="margin-top: 100px; background: #ffff; opacity: 0.95">
      <div class="row">
        <div class="col-sm">
        <h2>Witaj : {{ user }}</h2></br></br>
        <h2 style="text-align: center">Twoje reklamy:</h2>
        {% for adv in ads %}
        <div class="alert alert-info" role="alert">
          <b><h2><a href="{% url 'accounts:advertisement_detail' id=adv.pk %}">{{ adv }}</a></h2> </b> status:{% if adv.status == 'active' %}
                <b><span class="badge badge-success">{{ adv.status }}</span></b> </br>{% else %}
                <b><span class="badge badge-secondary">{{ adv.status }}</span></b> </br>{% endif %}
                liczba użytkowników korzystających z
                reflinka: <span class="badge badge-light">{{ adv.adver.count }}</span>
        </div>
        {% endfor %}

        </div>
        <div class="col-sm">
        <h2>Balans : {{ user_profile.balance }} </h2></h2></br></br>
        <h2>Aktualnie przekierowania:</h2>
        {% for tr in transaction %}
        <div class="alert alert-primary" role="alert">
            <p>Tytuł : {{ tr.advertisement_id.title }}</p>
            Link do strony : {{ tr.url_link }}</br>
            Liczba przekierowań :{{ tr.numbers_of_click }}</div>
        {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}