ad_page/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView

from ad_page import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="home"),
    path('admin/', admin.site.urls),
    path('ads/', include('ads.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

ads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'ads'

urlpatterns = [
                  path('', views.ads_list_view, name='list'),
                  path('add_advertisement/', views.add_advertisement, name='add_advertisement'),
                  path('<int:id>/', views.ads_detail_view, name='detail'),
                  path('transaction/<int:pk>/', views.create_transaction_view, name='create_transaction'),
                  path('reflink/<slug:slg>/', views.redirect_view, name='redirect'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import UserProfile

STATUS_CHOICES = (
    ('inactive', 'Nieaktywny'),
    ('active', 'Aktywny'),
)


class Advertisement(models.Model):
    title = models.CharField(max_length=200)
    action_value = models.DecimalField(max_digits=10, decimal_places=4)
    page_url = models.URLField()
    img = models.ImageField(default='default.png', blank=True, )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='Advertisement')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='inactive')

    def __str__(self):
        return self.title


class Transaction(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='transaction')
    advertisement_id = models.ForeignKey(Advertisement, on_delete=models.CASCADE, default=None, related_name='adver')
    url_link = models.URLField()
    numbers_of_click = models.IntegerField()

ads/forms.py
from django import forms
from ads.models import Advertisement


class AdvertisementForm(forms.ModelForm):
    title = forms.CharField(max_length=200, help_text="Please enter the title.")
    action_value = forms.DecimalField(help_text="Please enter action value.", min_value=0)
    page_url = forms.URLField(help_text="Please enter your page url.")
    img = forms.ImageField(help_text="Please enter image of your ad.")

    class Meta:
        model = Advertisement
        fields = ['title', 'action_value', 'page_url', 'img']

ads/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from accounts.models import UserProfile
from ads.forms import AdvertisementForm
from ads.models import Advertisement, Transaction


def ads_list_view(request):
    ads = Advertisement.objects.all()
    return render(request, 'ads/ads_list.html', {'ads': ads})


@login_required(login_url="/accounts/login/")
def add_advertisement(request):
    if request.method == 'POST':
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            instance.status = 'active'
            instance.save()
            return redirect('ads:list')
    else:
        form = AdvertisementForm()
    return render(request, 'ads/add_advertisement.html', {'form': form})


def ads_detail_view(request, id):
    adv = Advertisement.objects.get(pk=id)
    return render(request, 'ads/ads_detail.html', {'adv': adv})


@login_required(login_url="/accounts/login/")
def create_transaction_view(request, pk):
    user_id = request.user.id
    exist = Transaction.objects.filter(user_id=user_id, advertisement_id=pk).count()
    if not exist:
        url = "http://konandestylator.pythonanywhere.com/ads/reflink/{}-{}".format(user_id, pk)
        adv = Advertisement.objects.get(id=pk)
        transaction = Transaction()
        transaction.user_id = request.user
        transaction.url_link = url
        transaction.advertisement_id = adv
        transaction.numbers_of_click = 0
        transaction.save()
        return redirect('accounts:profile')
    else:
        return redirect('ads:list')


def redirect_view(request, slg):
    user_id, adv_id = slg.split("-")
    transaction = Transaction.objects.get(user_id=user_id, advertisement_id=adv_id)
    transaction.numbers_of_click = 1 + transaction.numbers_of_click
    url = transaction.advertisement_id.page_url
    value = transaction.advertisement_id.action_value
    owner_id = transaction.advertisement_id.owner
    owner = UserProfile.objects.get(user_id=owner_id)
    if owner.balance - value < 0:
        transaction.save()
        return redirect('home')
    else:
        owner.balance = owner.balance - value
        owner.save()
        user = UserProfile.objects.get(user_id=user_id)
        user.balance = user.balance + value
        user.save()
        transaction.save()
        return redirect(url)

ads/templates/ads/add_advertisement.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block title %} Login {% endblock %}

{% block content %}
<div class="loginbox" style="height: 780px; width: 500px">
            <h1>Add a advertisement</h1>
            <form class="site-form" method="POST" action="{% url 'ads:add_advertisement' %}" enctype="multipart/form-data">
              {% csrf_token %}
                {{ form.as_p }}
                <br /><br />
                <input type="submit" name="submit" value="Create Advertisement">
            </form>
        </div>
{% endblock %}

ads/templates/ads/ads_detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}

{% block title_block %}
    Advertisement detail
{% endblock %}

{% block content %}
    <div class="container rounded" style="margin-top: 100px; background: #ffff; opacity: 0.95"><br />
      <div class="advertisement">
        <p>Dodane przez: {{ adv.owner.username }}</p>
        <p><img src="{{ adv.img.url }}" width="500"></p>
        <p><div class="p-3 mb-2 bg-primary text-white rounded" role="alert">Adres URL : {{ adv.page_url }}</div></p>
        <p><div class="p-3 mb-2 bg-info text-white rounded" role="alert">Wartość akcji : {{ adv.action_value }}</div></p>
    </div>

    <button><a href="{% url 'ads:create_transaction' adv.pk %}">Generuj reflink</a></button><br /><br />
</div>

{% endblock %}

ads/templates/ads/ads_list.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}

{% block title_block %}
    Advertisement list
{% endblock %}

{% block content %}
    <br /><br /><br />
    {% for adv in ads %}
    {% if adv.status == 'inactive' %}
    {% else %}
        <div class="container bg-secondary text-white rounded"><br />
              <div class="row">
          <div class="col-4">
            <p><img src="{{ adv.img.url }}" class="img-thumbnail rounded float-left" width="230"></p>
          </div>
          <div class="col-8">
            <h3>
                Tytuł: {{ adv.title }} <a class="btn btn-primary" href="{% url 'ads:detail' adv.pk %}" role="button">Dodaj</a>
            </h3>
            <div class="p-3 mb-2 bg-info text-white rounded" role="alert">
            Wartość akcji: {{ adv.action_value}}
            </div>

            <p>Właściciel: {{ adv.owner.username }}</p>
          </div>
        </div>
        <br />
      </div>
      <br /><br />
    {% endif %}
    {% endfor %}



{% endblock %}