accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/advertisement_detail/<int:id>/', views.advertisement_detail, name='advertisement_detail'),
    path('profile/advertisement_detail/adv_edit/<int:id>', views.adv_edit, name='adv_edit'),

]

ad_page/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView

from ad_page import settings

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="home"),
    path('admin/', admin.site.urls),
    path('ads/', include('ads.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

ads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'ads'

urlpatterns = [
                  path('', views.ads_list_view, name='list'),
                  path('add_advertisement/', views.add_advertisement, name='add_advertisement'),
                  path('<int:id>/', views.ads_detail_view, name='detail'),
                  path('transaction/<int:pk>/', views.create_transaction_view, name='create_transaction'),
                  path('reflink/<slug:slg>/', views.redirect_view, name='redirect'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block cssblock %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ads:list' %}">Lista reklam <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ads:add_advertisement' %}">Dodaj reklame</a>
            </li>

        </ul>

        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profil {{ user.username }} <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout <span
                            class="sr-only">(current)</span></a>
                </li>

        {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Signup<span class="sr-only">(current)</span></a>
                </li>
        {% endif %}
        </ul>
    </div>
</nav>

    {% block content %}
    {% endblock %}



<footer class="container">
    <p>&copy; RR-Company 2017-2018</p>
</footer>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block cssblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
{% endblock %}
{% block title_block %}
Witajcie
{% endblock %}

{% block content %}
    <div class="container rounded" style="margin-top: 100px; background: #ffff; opacity: 0.95"><br />
      <h1> Strona tworzona z pasją dla reklamodawców i reklamobiorców.</h1><br/><br/>
      <p> Nasza strona umożliwia zarządzanie reklamami wyświetlanymi na Państwa stronach w indywidualnie kontrolowany sposób.</p>
      <ul>
        <li>jasne i czytelne opłaty za akcję, bez zbędnych informacji,<br/><img src="{% static 'przyklad.jpg' %}"></li><br/>
        <li>minimalistycznie zaprojektowane UI pozwala szybkie zarządzanie reklamami,<br/><img src="{% static 'przyklad2.jpg' %}" width="1000"></li>
        <li>oraz wiele innych innowacyjnych, nowoczesnych i autorskich rozwiązań. </li><br/>
      </ul>
    </div> <!-- /container -->
{% endblock %}